### ISSUE TITLE
Possible to customize the chat message prefix?

### ISSUE THREAD

**Issue by mibby** [PyvesB/AntiWorldFly#6]

**Comment by PyvesB** [comment]
Hello,

Are you talking about the plugin's circular icon?

Cheers,

Pyves

**Comment by mibby** [comment]
That'd be the one, yep.

**Comment by PyvesB** [comment]
Hello @mibby,

I have implemented a new version that adds an option to do this, an option for issue #7 and some additional fixes.

[AntiWorldFly-2.2.zip](https://github.com/PyvesB/AntiWorldFly/files/522578/AntiWorldFly-2.2.zip)

 Could you please test it and confirm that everything has the expected behaviour?

EDIT 26/10: ticket closed, feature now released.

Cheers,

Pyves
